### ISSUE TITLE
Inline fractions are sometime interpreted as bullet points

### ISSUE THREAD

**Issue by fariedabuzaid** [texmacs/markdown#42]
Happens preferably (but non-deterministically) if multiple fractions are used in a single inline math environment

In [Browser:]
![image](https://user-images.githubusercontent.com/28652659/168069609-58b0a902-e9af-4c6d-aaf0-47b1c2c27969.png)

In TeXmacs:
![image](https://user-images.githubusercontent.com/28652659/168070198-ec8a0299-b181-4172-abc8-919b1d32492d.png)

@mdbenito 
see also https://gitlab.com/iaai/appliedAI/transferlab/tfl-website/-/commit/90a541c594aa7563cc3689d22725f30a68738cc9

**Comment by mdbenito** [comment]
The problem is not the inline fraction but the fact that the math is broken into multiple lines and one line starts with a hyphen, which is interpreted by the markdown renderer as a bullet point. In theory, there is a safeguard against this in https://github.com/texmacs/markdown/blob/9ef379264847ce8bb9adbb0acfa515fa5d6757ae/progs/markdownout.scm#L238-L245, but it seems not to work in this case.
